// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6PH7ywnnVer88772oTzWJnxICaLNtW9k',
    appId: '1:1071619500164:web:1daac89f1e03d4b33efad1',
    messagingSenderId: '1071619500164',
    projectId: 'meeme-2c986',
    authDomain: 'meeme-2c986.firebaseapp.com',
    storageBucket: 'medical-67f6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6PH7ywnnVer88772oTzWJnxICaLNtW9k',
    appId: '1:1071619500164:web:1daac89f1e03d4b33efad1',
    messagingSenderId: '1071619500164',
    projectId: 'meeme-2c986',
    storageBucket: 'medical-67f6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6PH7ywnnVer88772oTzWJnxICaLNtW9k',
    appId: '1:1071619500164:web:1daac89f1e03d4b33efad1',
    messagingSenderId: '1071619500164',
    projectId: 'meeme-2c986',
    storageBucket: 'medical-67f6f.appspot.com',
  );
}
