// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//       apiKey: "AIzaSyD7mIN8SBquPfoYJ6ZuHRI-kjpBGKnXfPc",
//       authDomain: "trading-app-1bc0e.firebaseapp.com",
//       projectId: "trading-app-1bc0e",
//       storageBucket: "trading-app-1bc0e.firebasestorage.app",
//       messagingSenderId: "1002153357322",
//       appId: "1:1002153357322:web:9531afcfe83441206e6ff3",
//       measurementId: "G-LE4EB3Q4SM");

//   static const FirebaseOptions android = FirebaseOptions(
//       apiKey: "AIzaSyD7mIN8SBquPfoYJ6ZuHRI-kjpBGKnXfPc",
//       authDomain: "trading-app-1bc0e.firebaseapp.com",
//       projectId: "trading-app-1bc0e",
//       storageBucket: "trading-app-1bc0e.firebasestorage.app",
//       messagingSenderId: "1002153357322",
//       appId: "1:1002153357322:web:9531afcfe83441206e6ff3",
//       measurementId: "G-LE4EB3Q4SM");

//   static const FirebaseOptions ios = FirebaseOptions(
//       apiKey: "AIzaSyD7mIN8SBquPfoYJ6ZuHRI-kjpBGKnXfPc",
//       authDomain: "trading-app-1bc0e.firebaseapp.com",
//       projectId: "trading-app-1bc0e",
//       storageBucket: "trading-app-1bc0e.firebasestorage.app",
//       messagingSenderId: "1002153357322",
//       appId: "1:1002153357322:web:9531afcfe83441206e6ff3",
//       measurementId: "G-LE4EB3Q4SM");
// }
