// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7mIN8SBquPfoYJ6ZuHRI-kjpBGKnXfPc',
    appId: '1:1002153357322:web:9531afcfe83441206e6ff3',
    messagingSenderId: '1002153357322',
    projectId: 'trading-app-1bc0e',
    authDomain: 'trading-app-1bc0e.firebaseapp.com',
    storageBucket: 'trading-app-1bc0e.firebasestorage.app',
    measurementId: 'G-LE4EB3Q4SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaP2NAVTcObiNKKIxUKbuLWEGD7blXrHg',
    appId: '1:1002153357322:android:81d9a88c8e4dfde86e6ff3',
    messagingSenderId: '1002153357322',
    projectId: 'trading-app-1bc0e',
    storageBucket: 'trading-app-1bc0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRr20cZoB-xl1i32Kxc9OU3Iiyi0l2Zq4',
    appId: '1:1002153357322:ios:80fa5c36522d4e4c6e6ff3',
    messagingSenderId: '1002153357322',
    projectId: 'trading-app-1bc0e',
    storageBucket: 'trading-app-1bc0e.firebasestorage.app',
    androidClientId: '1002153357322-p11g412o7fvpn6vu5ij2b67hb7faboap.apps.googleusercontent.com',
    iosClientId: '1002153357322-i1uevjmmnpfsjciu6c84sp57fu0sv3qp.apps.googleusercontent.com',
    iosBundleId: 'com.trading.tradingapp',
  );
}
